# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClawWrap < Formula
  desc "Credential proxy for CLI tools — secrets never enter the sandbox"
  homepage "https://github.com/dedene/claw-wrap"
  version "0.1.0"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/dedene/claw-wrap/releases/download/v0.1.0/claw-wrap_0.1.0_linux_amd64.tar.gz"
    sha256 "06ce24cd5aa7d32edf8f677bc3648d8d4d0ab8f23d9f6f32346b71feeac03f81"
    def install
      bin.install "claw-wrap"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dedene/claw-wrap/releases/download/v0.1.0/claw-wrap_0.1.0_linux_arm64.tar.gz"
    sha256 "e0e41daf6ac5b0b098f5e951d0fa68163a0a9f84724e865ca174a10d43a3c9c1"
    def install
      bin.install "claw-wrap"
    end
  end

  test do
    system "#{bin}/claw-wrap", "version"
  end
end
