# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notion < Formula
  desc "CLI for the Notion API"
  homepage "https://github.com/dedene/notion-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_amd64.tar.gz"
      sha256 "80a955e8a3646a2c62d2f79c2d54259d25e464c22778ea9a792be81478e5b2ac"

      def install
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_arm64.tar.gz"
      sha256 "786cf85f5b775cb98c805d759858ca12a0f6a32ebdc9fa14d4bff0dcb03e74e4"

      def install
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_amd64.tar.gz"
      sha256 "0de5435a4692f15e7aa4c20a466f80984d64122763c3206f7dca81ad2ee7f352"
      def install
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_arm64.tar.gz"
      sha256 "a1b02001151917c35388628edebd7c2138b33620a65eb7132a80652e988b8f3e"
      def install
        bin.install "notion"
      end
    end
  end

  test do
    system "#{bin}/notion", "version"
  end
end
