# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawpoll < Formula
  desc "StrawPoll CLI - Create and manage polls from the command line"
  homepage "https://github.com/dedene/strawpoll-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.1/strawpoll_darwin_amd64.tar.gz"
      sha256 "4597680bcdfd3a5a752ccc3a11ca4cca6b15355ee098483700a4b32a6b0d59dc"

      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.1/strawpoll_darwin_arm64.tar.gz"
      sha256 "41569f888c43864c6d583e9d2b787508a22dd84751c931c9ef0dd638c1cb72d9"

      def install
        bin.install "strawpoll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.1/strawpoll_linux_amd64.tar.gz"
      sha256 "406c019c869e1a2cf41140cadc1ff5feb4098cba520c3e7a25353f3331be8f88"
      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.1/strawpoll_linux_arm64.tar.gz"
      sha256 "7ee07a7d3a3cd429cdc7dcad58d2f9900a4403dd62c39989bfff58baf81d4cf4"
      def install
        bin.install "strawpoll"
      end
    end
  end
end
