# This file was generated by GoReleaser. DO NOT EDIT.
cask "strawpoll" do
  name "strawpoll"
  desc "StrawPoll CLI - Create and manage polls from the command line"
  homepage "https://github.com/dedene/strawpoll-cli"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "strawpoll"

  on_macos do
    on_intel do
      url "https://github.com/dedene/strawpoll-cli/releases/download/v#{version}/strawpoll_darwin_amd64.tar.gz"
      sha256 "8586557beab7b1368d5defb20dc432a42bba469ac6c297a94b3502bcc520e7bc"
    end
    on_arm do
      url "https://github.com/dedene/strawpoll-cli/releases/download/v#{version}/strawpoll_darwin_arm64.tar.gz"
      sha256 "0c787ac12972e9aa4bcc16a0e51e398745d41ccf4923c4779ae91cd429f4bae4"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dedene/strawpoll-cli/releases/download/v#{version}/strawpoll_linux_amd64.tar.gz"
      sha256 "f118165f3c0b6dc34389928d36b9f865e0e4c80e0ac4b5863ee01303ecd49ec8"
    end
    on_arm do
      url "https://github.com/dedene/strawpoll-cli/releases/download/v#{version}/strawpoll_linux_arm64.tar.gz"
      sha256 "0d45bf09a6e36495cb2a36491599488f633fb4e7026cc261c25fe946addb135d"
    end
  end

  # No zap stanza required
end
