# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClawWrap < Formula
  desc "Credential proxy for CLI tools — secrets never enter the sandbox"
  homepage "https://github.com/dedene/claw-wrap"
  version "0.4.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.2/claw-wrap_0.4.2_darwin_amd64.tar.gz"
      sha256 "ce760a059334997eca84cd47cc46ffa9f24f01e7dc11c3af430eecbfffcf118d"

      def install
        bin.install "claw-wrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.2/claw-wrap_0.4.2_darwin_arm64.tar.gz"
      sha256 "b2ef0f13d7b2e337d693dbc977e09dbe90f018f0947a7c9dbaead32c346f3ab4"

      def install
        bin.install "claw-wrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.2/claw-wrap_0.4.2_linux_amd64.tar.gz"
      sha256 "82638ef4e1c54f02756094c78b51c1ad4518d447faaba516d09b186381de4b9e"
      def install
        bin.install "claw-wrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.2/claw-wrap_0.4.2_linux_arm64.tar.gz"
      sha256 "98a4e77747b7fa0a266fee1f986eb17189c56abca701d860c904b9e9b44bcb10"
      def install
        bin.install "claw-wrap"
      end
    end
  end

  test do
    system "#{bin}/claw-wrap", "version"
  end
end
