# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClawWrap < Formula
  desc "Credential proxy for CLI tools — secrets never enter the sandbox"
  homepage "https://github.com/dedene/claw-wrap"
  version "0.4.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.4/claw-wrap_0.4.4_darwin_amd64.tar.gz"
      sha256 "7ba56917c1323027264a604e4372ade9f95a2171bb5088df44640021bdfc9c8c"

      def install
        bin.install "claw-wrap"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.4/claw-wrap_0.4.4_darwin_arm64.tar.gz"
      sha256 "7595212f85bd70526ac9cd14e55c0a965475cfb5e4f1aba356967983f3c9c81d"

      def install
        bin.install "claw-wrap"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.4/claw-wrap_0.4.4_linux_amd64.tar.gz"
      sha256 "2b90436d65176898c3124a3a9e0e77193d45267980bce6af509b6118a9428b73"
      def install
        bin.install "claw-wrap"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/claw-wrap/releases/download/v0.4.4/claw-wrap_0.4.4_linux_arm64.tar.gz"
      sha256 "ce11e7a024bd9cb1d9b8831125f3ff407f9138bc6902a811c3af45a63782c8a3"
      def install
        bin.install "claw-wrap"
      end
    end
  end

  test do
    system "#{bin}/claw-wrap", "version"
  end
end
