# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClawWrap < Formula
  desc "Credential proxy for CLI tools — secrets never enter the sandbox"
  homepage "https://github.com/dedene/claw-wrap"
  version "0.1.6"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/dedene/claw-wrap/releases/download/v0.1.6/claw-wrap_0.1.6_linux_amd64.tar.gz"
    sha256 "153a451bd51631cd7bb6223a6cb8ae9c3b527e1fd26ae4205cede53f5863d48c"
    def install
      bin.install "claw-wrap"
    end
  end
  if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/dedene/claw-wrap/releases/download/v0.1.6/claw-wrap_0.1.6_linux_arm64.tar.gz"
    sha256 "ead193d610969c49c88ff415d3a2d826b462a00f79c4a221321c0febed6458b8"
    def install
      bin.install "claw-wrap"
    end
  end

  test do
    system "#{bin}/claw-wrap", "version"
  end
end
