# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Delijn < Formula
  desc "CLI for De Lijn - Flemish public transport departures, stops, and routes"
  homepage "https://github.com/dedene/delijn-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/delijn-cli/releases/download/v0.1.0/delijn_0.1.0_darwin_amd64.tar.gz"
      sha256 "f91cd2eb456be870847df98c60b75c62d9517b86cf863dd583fafa1a032473fc"

      def install
        bin.install "delijn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/delijn-cli/releases/download/v0.1.0/delijn_0.1.0_darwin_arm64.tar.gz"
      sha256 "e1def38d3fd287bef78e32b3d2ce2d53ebd323166b4f71cfbdcb6674d760858a"

      def install
        bin.install "delijn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/delijn-cli/releases/download/v0.1.0/delijn_0.1.0_linux_amd64.tar.gz"
      sha256 "54402da21c63353bbc0d3e8797201e8d3f807ecdbae232ee6acb5454159fffb6"
      def install
        bin.install "delijn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/delijn-cli/releases/download/v0.1.0/delijn_0.1.0_linux_arm64.tar.gz"
      sha256 "03049b2d3a3be993566a3c0c3bc97a96ffd162cdaf16f400e9329c51fcac010f"
      def install
        bin.install "delijn"
      end
    end
  end

  test do
    system "#{bin}/delijn", "--version"
  end
end
