# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frontcli < Formula
  desc "CLI for Front.app - manage conversations, messages, contacts, and more"
  homepage "https://github.com/dedene/frontapp-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.3/frontcli_0.1.3_darwin_amd64.tar.gz"
      sha256 "9b89a779564a7b41b763666ed6ea00225d8a247105ec627bc2ff7125ba90f1f2"

      def install
        bin.install "frontcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.3/frontcli_0.1.3_darwin_arm64.tar.gz"
      sha256 "505ae6969225d3b1ec2aad8e3505fde0cf8789adfb4311dab40df312e406cf4b"

      def install
        bin.install "frontcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.3/frontcli_0.1.3_linux_amd64.tar.gz"
      sha256 "8c8d77a7c1fb5753068b288f6c18c236a46f89a4c7d4afdb8c4724fa80831c10"
      def install
        bin.install "frontcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.3/frontcli_0.1.3_linux_arm64.tar.gz"
      sha256 "ed143bf6c4bd463b09f45364af5f48313bf34caed07c5b08675d929bfc8a6f14"
      def install
        bin.install "frontcli"
      end
    end
  end

  test do
    system "#{bin}/frontcli", "--version"
  end
end
