# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Frontcli < Formula
  desc "CLI for Front.app - manage conversations, messages, contacts, and more"
  homepage "https://github.com/dedene/frontapp-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.1/frontcli_0.1.1_darwin_amd64.tar.gz"
      sha256 "a2490d0cbf158d28b664aa385799af1211d945e239eca928af0443f8565d48f8"

      def install
        bin.install "frontcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.1/frontcli_0.1.1_darwin_arm64.tar.gz"
      sha256 "2de7f5fe45d51de6f86c6f58f149d3884204008b2e71e256112ce41f257bd36a"

      def install
        bin.install "frontcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.1/frontcli_0.1.1_linux_amd64.tar.gz"
      sha256 "4d150d2c0fa87d70749c227d804d8bc1abd0c0cd606253bdc8e179c9fdbc703e"
      def install
        bin.install "frontcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/frontapp-cli/releases/download/v0.1.1/frontcli_0.1.1_linux_arm64.tar.gz"
      sha256 "88f2eaec3066bf372b3357992b51756b0f1ae3773646a7b168910ddd6bbf6a3c"
      def install
        bin.install "frontcli"
      end
    end
  end

  test do
    system "#{bin}/frontcli", "--version"
  end
end
