# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Harvestcli < Formula
  desc "Harvest time tracking CLI"
  homepage "https://github.com/dedene/harvest-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/harvest-cli/releases/download/v0.1.0/harvest-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "3dad341cf9d7d175dec57b97b121573da208b8acdae75d775ee936a6b4a88711"

      def install
        bin.install "harvest"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/harvest-cli/releases/download/v0.1.0/harvest-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "b20ca41af56c46043ccbff9dad4b0bb9d7e0a73ba36c185dabacfd8f1d7ba1ee"

      def install
        bin.install "harvest"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/harvest-cli/releases/download/v0.1.0/harvest-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "4255326323a6a81dff3cf5c507cd070f814b89d402209d145297a38482d210ed"
      def install
        bin.install "harvest"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/harvest-cli/releases/download/v0.1.0/harvest-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "c36cb7500169cfa8c4953cf586806c1f29e043be479adedf016048359f5d2b66"
      def install
        bin.install "harvest"
      end
    end
  end

  test do
    system "#{bin}/harvest", "version"
  end
end
