# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Irail < Formula
  desc "CLI for Belgian railway (NMBS/SNCB) schedules"
  homepage "https://github.com/dedene/irail-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/irail-cli/releases/download/v0.1.0/irail-cli_Darwin_x86_64.tar.gz"
      sha256 "9094c484bf2edb42926013703eba99f714dc5d8a62684028df0daadd940f00c0"

      def install
        bin.install "irail"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/irail-cli/releases/download/v0.1.0/irail-cli_Darwin_arm64.tar.gz"
      sha256 "dda831d2f3d6f381d2a5d810362a0a308180a745f67b638a7f3e5b5a15edbefc"

      def install
        bin.install "irail"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/irail-cli/releases/download/v0.1.0/irail-cli_Linux_x86_64.tar.gz"
      sha256 "6785c9ab2192d3d331f0eb86c18a912f438f1512f10211acf96b01a83297429d"
      def install
        bin.install "irail"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/irail-cli/releases/download/v0.1.0/irail-cli_Linux_arm64.tar.gz"
      sha256 "555ce8c94cd51a96228d699204fdf99f9adedaf0d3b26a5fe09fe2585dfb57e2"
      def install
        bin.install "irail"
      end
    end
  end

  test do
    system "#{bin}/irail", "version"
  end
end
