# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kmi < Formula
  desc "CLI for KMI/IRM Belgian weather API - forecasts, radar, warnings, pollen"
  homepage "https://github.com/dedene/kmi-irm-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.1/kmi_0.1.1_darwin_amd64.tar.gz"
      sha256 "1fd7bc346cd0bf99b9c4d9119a11174b789c3e99022a28968b3a2d8359024dcf"

      def install
        bin.install "kmi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.1/kmi_0.1.1_darwin_arm64.tar.gz"
      sha256 "3fac9d458e84ea17f2e9f8e1a0bd2334213000c402176d48c90e88eac0d6ba9d"

      def install
        bin.install "kmi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.1/kmi_0.1.1_linux_amd64.tar.gz"
      sha256 "c7aecd9cff41f92600c03890258827df27d4a78761d74a12fad8a38e06bc832b"
      def install
        bin.install "kmi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.1/kmi_0.1.1_linux_arm64.tar.gz"
      sha256 "168fa0b2f96e040d33467ef5c0efde1dcce19fe238fe78b1d91c0bd0b46ff8e2"
      def install
        bin.install "kmi"
      end
    end
  end

  test do
    system "#{bin}/kmi", "--version"
  end
end
