# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kmi < Formula
  desc "CLI for KMI/IRM Belgian weather API - forecasts, radar, warnings, pollen"
  homepage "https://github.com/dedene/kmi-irm-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.0/kmi_0.1.0_darwin_amd64.tar.gz"
      sha256 "8a5bbfd4e390e296b977377fcddcdc295357d28d747cda14546b30e70bd1b4de"

      def install
        bin.install "kmi"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.0/kmi_0.1.0_darwin_arm64.tar.gz"
      sha256 "9c45b3f52a4b5cb6dd6a5c967232195c861750e6a9d3bea07dbc4d732b188dca"

      def install
        bin.install "kmi"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.0/kmi_0.1.0_linux_amd64.tar.gz"
      sha256 "9eea82cb7a43ba26ba1aa11c2678baa7539124bfba599da734f271f8c851e7ab"
      def install
        bin.install "kmi"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/kmi-irm-cli/releases/download/v0.1.0/kmi_0.1.0_linux_arm64.tar.gz"
      sha256 "71e86e230739d6d32b38533cb8b7f854fbce5cf00c9e149c337750786edc8ad5"
      def install
        bin.install "kmi"
      end
    end
  end

  test do
    system "#{bin}/kmi", "--version"
  end
end
