# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lametric < Formula
  desc "CLI for LaMetric TIME/SKY - control your device from the command line"
  homepage "https://github.com/dedene/lametric-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.0/lametric_darwin_amd64.tar.gz"
      sha256 "9f333f16630aa25d3e7b3a39467df77e53174f380c86aaf2d62eb9b2acc8bb66"

      def install
        bin.install "lametric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.0/lametric_darwin_arm64.tar.gz"
      sha256 "1a9a39cebda0dceb08d416ef8981a5ef489993d418b51722b2f00c7e79d97b26"

      def install
        bin.install "lametric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.0/lametric_linux_amd64.tar.gz"
      sha256 "d3255d9b35d388781ecc884f58552f31b3c35a2c31e2fa442338c367b86c400f"
      def install
        bin.install "lametric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.0/lametric_linux_arm64.tar.gz"
      sha256 "519f00fa473744eb199f70a9b3631aa7f67fd2943fa93b9d3f08e7476fc14e4c"
      def install
        bin.install "lametric"
      end
    end
  end

  test do
    system "#{bin}/lametric", "--version"
  end
end
