# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lametric < Formula
  desc "CLI for LaMetric TIME/SKY - control your device from the command line"
  homepage "https://github.com/dedene/lametric-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.1/lametric_darwin_amd64.tar.gz"
      sha256 "6d8a2624ade323262d00227c9818bb33de1e6e708b6fbbab68bdbafb95bb8b34"

      def install
        bin.install "lametric"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.1/lametric_darwin_arm64.tar.gz"
      sha256 "d218b6c5467c433fd9673ddda6c784963a8d6d4d139e714cb9445c1276b4ac40"

      def install
        bin.install "lametric"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.1/lametric_linux_amd64.tar.gz"
      sha256 "2d0272a688ddcff33c94007bfe787ae56882b46fc9e5ec3366003e54a30e8919"
      def install
        bin.install "lametric"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/lametric-cli/releases/download/v0.1.1/lametric_linux_arm64.tar.gz"
      sha256 "1fb05759a400815f651e7d08d8adb83cedcf1387eef7f6d6077b0d55b6b4695b"
      def install
        bin.install "lametric"
      end
    end
  end

  test do
    system "#{bin}/lametric", "--version"
  end
end
