# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemelinkCli < Formula
  desc "Generate memes from the terminal"
  homepage "https://github.com/dedene/memelink-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/memelink-cli/releases/download/v0.1.0/memelink-cli_darwin_amd64.tar.gz"
      sha256 "e463dda8af1d8506fbc8042392a8e96f6c1c6fd4b9b1f1aae03d8c0e9031e0eb"

      def install
        bin.install "memelink"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/memelink-cli/releases/download/v0.1.0/memelink-cli_darwin_arm64.tar.gz"
      sha256 "c5feaaa0662c5a3538d595aa82d6b2f0bcfa7b1607ada06cca0ffc0dbb78f595"

      def install
        bin.install "memelink"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/memelink-cli/releases/download/v0.1.0/memelink-cli_linux_amd64.tar.gz"
      sha256 "d9b7543624835f45d0ba28263178366741d6a76a422b37baebe4939904b7f235"
      def install
        bin.install "memelink"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/memelink-cli/releases/download/v0.1.0/memelink-cli_linux_arm64.tar.gz"
      sha256 "039d807f028a446c589493e6d8463fed266f87e0a1cba40f2eff382268a1493f"
      def install
        bin.install "memelink"
      end
    end
  end
end
