# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Notion < Formula
  desc "CLI for the Notion API"
  homepage "https://github.com/dedene/notion-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_amd64.tar.gz"
      sha256 "9c5cbb53cefd2dcd84135d028b702effa38b4deab7db4cc825abfcbfab6a0308"

      def install
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_darwin_arm64.tar.gz"
      sha256 "76ea701cdd914ae0fb7d270838f218b39039ad274f451ccd71fc45b704d72608"

      def install
        bin.install "notion"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_amd64.tar.gz"
      sha256 "a3d08797558e5fad867513350bf377968318200b325ac0bb48aa9bf697da6425"
      def install
        bin.install "notion"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/notion-cli/releases/download/v0.1.0/notion_0.1.0_linux_arm64.tar.gz"
      sha256 "b766c1c4da5d5ced78212e1f3443acf2583c19c52ba8483c3f6c6f07e6790e3a"
      def install
        bin.install "notion"
      end
    end
  end

  test do
    system "#{bin}/notion", "version"
  end
end
