# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PontoCli < Formula
  desc "CLI for Ponto banking API - manage accounts, transactions, and syncs"
  homepage "https://github.com/dedene/ponto-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/ponto-cli/releases/download/v0.1.0/ponto-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "e1b561f5fbcf7bba80dfdedaf797f03e8cc4e1e50b7de2392ddf9adb0edc9a5c"

      def install
        bin.install "ponto"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/ponto-cli/releases/download/v0.1.0/ponto-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "7d5c058afdc41e90f3b3b8df133153b627a36dfcb1f9853787e9e9b273fc4d77"

      def install
        bin.install "ponto"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/ponto-cli/releases/download/v0.1.0/ponto-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "7689903d257ff20877a57d5bfc4e452b4f953282f12b19d454a68638e686ef2c"
      def install
        bin.install "ponto"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/ponto-cli/releases/download/v0.1.0/ponto-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "173feebf4b49fe51cd729c7ae2efebda404839d693d9d5ab0f4811277bffb4b8"
      def install
        bin.install "ponto"
      end
    end
  end

  test do
    system "#{bin}/ponto", "--version"
  end
end
