# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class RaindropCli < Formula
  desc "CLI for Raindrop.io - manage bookmarks, collections, and tags"
  homepage "https://github.com/dedene/raindrop-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/raindrop-cli/releases/download/v0.1.1/raindrop-cli_0.1.1_darwin_amd64.tar.gz"
      sha256 "a40d5a17051c0c383f8f6acb065da47c0b48d4e763fa645ad9982d99b230040e"

      def install
        bin.install "raindrop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/raindrop-cli/releases/download/v0.1.1/raindrop-cli_0.1.1_darwin_arm64.tar.gz"
      sha256 "fa94d47bbe752c5464733566bf8a7adbd3037be64984e0b19b1882fca96e0988"

      def install
        bin.install "raindrop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/raindrop-cli/releases/download/v0.1.1/raindrop-cli_0.1.1_linux_amd64.tar.gz"
      sha256 "0ac16da13f74211ddfae118a809dc70d688c63f1626d4e36ebda8a964a967438"
      def install
        bin.install "raindrop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/raindrop-cli/releases/download/v0.1.1/raindrop-cli_0.1.1_linux_arm64.tar.gz"
      sha256 "26b172b7baf27d811bd3186412122ad7a7469c62725230415032c692949b5326"
      def install
        bin.install "raindrop"
      end
    end
  end

  test do
    system "#{bin}/raindrop", "--version"
  end
end
