# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rr < Formula
  desc "RealtimeRegister CLI - Domain management from the command line"
  homepage "https://github.com/dedene/realtime-register-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/realtime-register-cli/releases/download/v0.1.0/rr_0.1.0_darwin_amd64.tar.gz"
      sha256 "7ade9bc2b864416b99330000581ed8263a57df9cf83e458021eca7785fcb27ba"

      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/realtime-register-cli/releases/download/v0.1.0/rr_0.1.0_darwin_arm64.tar.gz"
      sha256 "eb684ae999c89dd2ae568377d73f49f80c8972bef0e0a6d7ccaa811332201873"

      def install
        bin.install "rr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/realtime-register-cli/releases/download/v0.1.0/rr_0.1.0_linux_amd64.tar.gz"
      sha256 "acf4d8e9eb3d4417dae5d4fd4deccdc79a3295ec4fdf0280f94c7b512287f3eb"
      def install
        bin.install "rr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/realtime-register-cli/releases/download/v0.1.0/rr_0.1.0_linux_arm64.tar.gz"
      sha256 "91a7951028887b7d4e1769eb586f882b5c7cff4c3b858bad76c02a184fbb5647"
      def install
        bin.install "rr"
      end
    end
  end

  test do
    system "#{bin}/rr", "version"
  end
end
