# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawpoll < Formula
  desc "CLI for StrawPoll - create and manage polls from the command line"
  homepage "https://github.com/dedene/strawpoll-cli"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.3/strawpoll_darwin_amd64.tar.gz"
      sha256 "143f5f9e19755ddf784b02dcfb47005381542ea5177843cc9d9ba486a18b7f83"

      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.3/strawpoll_darwin_arm64.tar.gz"
      sha256 "466467b6abbadb0bf5981cc6ec8657f0e4f0f129cca56348e90f12bef92d7497"

      def install
        bin.install "strawpoll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.3/strawpoll_linux_amd64.tar.gz"
      sha256 "ebf146cdcbaf9b4a74ea2262de531b751b53a3e36ba37440097b6889f5f7c4d0"
      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.3/strawpoll_linux_arm64.tar.gz"
      sha256 "f7e4dad8f22ca0889327adcb2402771bf1ae46e81082f23da568ab1d1cf4508d"
      def install
        bin.install "strawpoll"
      end
    end
  end

  test do
    system "#{bin}/strawpoll", "--version"
  end
end
