# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Strawpoll < Formula
  desc "CLI for StrawPoll - create and manage polls from the command line"
  homepage "https://github.com/dedene/strawpoll-cli"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.5/strawpoll_darwin_amd64.tar.gz"
      sha256 "4b3090144dde6943ca4c45943aca99a461b87aedc7bb645d51ec73e0cc87c508"

      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.5/strawpoll_darwin_arm64.tar.gz"
      sha256 "05ff1a557d2dc49016a485c0977e16ee7085fba621f4878d4f7acf88c0146ea8"

      def install
        bin.install "strawpoll"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.5/strawpoll_linux_amd64.tar.gz"
      sha256 "1ebaaaf9302dbe9ceafb9e769cca1217a81545fe544be0afd6f62dcdce837fd4"
      def install
        bin.install "strawpoll"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/strawpoll-cli/releases/download/v0.1.5/strawpoll_linux_arm64.tar.gz"
      sha256 "c003a3f4ada0b46d2be1e3364852e0b6ac3b6711d9106db68c7960da04d9d130"
      def install
        bin.install "strawpoll"
      end
    end
  end

  test do
    system "#{bin}/strawpoll", "--version"
  end
end
