# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Yuki < Formula
  desc "Agent-friendly CLI for Yuki accounting SOAP webservices"
  homepage "https://github.com/dedene/yuki-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dedene/yuki-cli/releases/download/v0.1.0/yuki_0.1.0_darwin_amd64.tar.gz"
      sha256 "caab2f8b7a34ed1787400fda00a7fb20cda279d7b555b3d984ba05b0c8b0d9bb"

      define_method(:install) do
        bin.install "yuki"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dedene/yuki-cli/releases/download/v0.1.0/yuki_0.1.0_darwin_arm64.tar.gz"
      sha256 "1a28a9dc2d4224f7826d893fa7c4d630535a4c4a1cee08aa52708c5d841fc3d5"

      define_method(:install) do
        bin.install "yuki"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/yuki-cli/releases/download/v0.1.0/yuki_0.1.0_linux_amd64.tar.gz"
      sha256 "20d4cf79a6ed9333570e5f7a3449964bea199e8c6508ae2a45b4a2e0f2808c0e"
      define_method(:install) do
        bin.install "yuki"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dedene/yuki-cli/releases/download/v0.1.0/yuki_0.1.0_linux_arm64.tar.gz"
      sha256 "e208399a214fd5075f608301479ce53f1845585906977635156d16bc9095e908"
      define_method(:install) do
        bin.install "yuki"
      end
    end
  end

  test do
    system "#{bin}/yuki", "version"
  end
end
